"""Tool 6 — Observation Computer (batched multi-world Newton FK + full physics).

Replays sequences generated by generate_sequences.py and extracts the full
47-dim RL observation vector per frame — identical to what FrankaCubePickEnvCfg
would present to the policy during training.

Architecture mirrors replay_sequences.py exactly (same Newton model, same
physics parameters, same batched multi-world setup). The only difference is
the output: instead of per-frame rewards, each frame stores the full obs vector.

Observation vector (47 dims, matching FrankaCubePickEnvCfg.ObservationsCfg)
---------------------------------------------------------------------------
  cube_pos  (3) : cube XYZ in robot root frame  [m]
  cube_quat (4) : cube orientation in robot root frame  [xyzw — Newton convention]
  ee_pos    (3) : EE position in robot root frame  [m]
  ee_quat   (4) : EE orientation in robot root frame  [xyzw]
  ee_linvel (3) : EE linear velocity in robot root frame  [m/s]
  ee_angvel (3) : EE angular velocity in robot root frame  [rad/s]
  joint_pos (9) : arm (7) + finger (2) joint positions  [rad / m]
  joint_vel (9) : arm (7) + finger (2) joint velocities  [rad/s / m/s]
  last_action(9): joint_pos_cmd at this step  (RL last_action is previous step;
                  scripted sequences use current step's IK command as proxy)

Robot root frame:
  Robot is fixed at world origin with identity rotation.
  → robot root frame == world frame for this task.
  → No rotation transformation needed: cube_pos_b = cube_pos_w − robot_pos_w.

Newton conventions:
  Quaternion format: [qx, qy, qz, qw]  (xyzw)
  body_qd layout: [omega_x, omega_y, omega_z, vx, vy, vz]  (angular then linear, world frame)

Usage
-----
python compute_observations.py \\
    --input  data/validation/reference_ik_sequences.json \\
    --output data/validation/reference_ik_observations.json \\
    [--num-worlds 16]
"""

import argparse
import datetime
import sys
from pathlib import Path

import numpy as np
import warp as wp

import newton

sys.path.insert(0, str(Path(__file__).parent))
from _common.sequence_schema import label_description, load_sequences

_TASK_ROOT   = Path(__file__).parent.parent
_OUTPUTS_DIR = _TASK_ROOT / "data" / "validation"

# ---------------------------------------------------------------------------
# Panda URDF
# ---------------------------------------------------------------------------

_FRANKA_URDF_CANDIDATES = [
    Path(
        "/home/horde/micromamba/envs/env_isaaclab/lib/python3.11/site-packages/"
        "isaacsim/exts/isaacsim.asset.importer.urdf/data/urdf/robots/"
        "franka_description/robots/panda_arm_hand.urdf"
    ),
]

_PANDA_HAND_BODY_LABEL = "panda_hand"

# ---------------------------------------------------------------------------
# Physics constants — MUST match generate_sequences.py and replay_sequences.py
# ---------------------------------------------------------------------------

_ARM_KE          = [4500, 4500, 3500, 3500, 2000, 2000, 2000]
_ARM_KD          = [450,  450,  350,  350,  200,  200,  200]
_FINGER_KE       = [100,  100]
_FINGER_KD       = [10,   10]
_ARM_ARMATURE    = [0.30, 0.30, 0.30, 0.30, 0.11, 0.11, 0.11]
_FINGER_ARMATURE = [0.15, 0.15]
_ARM_EFFORT      = [87.0, 87.0, 87.0, 87.0, 12.0, 12.0, 12.0]
_FINGER_EFFORT   = [100.0, 100.0]

_CONTACT_KE  = 5.0e4
_CONTACT_KD  = 5.0e2
_CONTACT_KF  = 1.0e3
_CONTACT_MU  = 0.75

_N_ROBOT_JOINTS       = 9       # 7 arm + 2 finger
_N_SUBSTEPS_PER_FRAME = 10      # must match generator
_SUB_DT               = 0.002   # 2ms per substep → 20ms per frame

_HOME_JOINT_Q = [
    -3.6802115e-03,
     2.3901723e-02,
     3.6804110e-03,
    -2.3683236e+00,
    -1.2918962e-04,
     2.3922248e+00,
     7.8549200e-01,
     0.04,
     0.04,
]

_CUBE_HALF_SIZE = 0.025
_CUBE_DENSITY   = 400.0

# ---------------------------------------------------------------------------
# Observation layout
# ---------------------------------------------------------------------------

OBS_NAMES = [
    # cube_pos in robot root frame (= world frame for this task)
    "cube_x", "cube_y", "cube_z",
    # cube_quat [xyzw]
    "cube_qx", "cube_qy", "cube_qz", "cube_qw",
    # ee_pos in robot root frame
    "ee_x", "ee_y", "ee_z",
    # ee_quat [xyzw]
    "ee_qx", "ee_qy", "ee_qz", "ee_qw",
    # ee linear velocity in robot root frame [m/s]
    "ee_vx", "ee_vy", "ee_vz",
    # ee angular velocity in robot root frame [rad/s]
    "ee_wx", "ee_wy", "ee_wz",
    # arm joint positions (7)
    "j0", "j1", "j2", "j3", "j4", "j5", "j6",
    # finger joint positions (2)
    "f0", "f1",
    # arm joint velocities (7) [rad/s]
    "jv0", "jv1", "jv2", "jv3", "jv4", "jv5", "jv6",
    # finger joint velocities (2) [m/s]
    "fv0", "fv1",
    # last action = joint_pos_cmd at this step (9)
    "act0", "act1", "act2", "act3", "act4", "act5", "act6", "act_f0", "act_f1",
]  # 47 total

assert len(OBS_NAMES) == 47


# ---------------------------------------------------------------------------
# Model building — verbatim from replay_sequences.py
# ---------------------------------------------------------------------------

def _find_panda_urdf() -> Path:
    for p in _FRANKA_URDF_CANDIDATES:
        if p.exists():
            return p
    raise FileNotFoundError("Panda URDF not found. Install Isaac Sim pip package.")


def build_robot_builder(urdf_path: Path) -> tuple:
    mb = newton.ModelBuilder()
    newton.solvers.SolverMuJoCo.register_custom_attributes(mb)
    mb.add_urdf(str(urdf_path), floating=False, enable_self_collisions=False,
                parse_visuals_as_colliders=False)

    hand_local_idx    = next(i for i, k in enumerate(mb.body_label) if _PANDA_HAND_BODY_LABEL in k)
    left_finger_body  = next(i for i, k in enumerate(mb.body_label) if "leftfinger"  in k)
    right_finger_body = next(i for i, k in enumerate(mb.body_label) if "rightfinger" in k)

    gravcomp_dof = mb.custom_attributes["mujoco:jnt_actgravcomp"]
    if gravcomp_dof.values is None:
        gravcomp_dof.values = {}
    for dof_idx in range(7):
        gravcomp_dof.values[dof_idx] = True

    gravcomp_body = mb.custom_attributes["mujoco:gravcomp"]
    if gravcomp_body.values is None:
        gravcomp_body.values = {}
    for body_idx in range(2, mb.body_count):
        gravcomp_body.values[body_idx] = 1.0

    for i in range(len(mb.shape_body)):
        if mb.shape_body[i] >= 0:
            mb.shape_collision_group[i] = 2

    _cfg_fbox = newton.ModelBuilder.ShapeConfig()
    _cfg_fbox.ke = _CONTACT_KE
    _cfg_fbox.kd = _CONTACT_KD
    _cfg_fbox.kf = _CONTACT_KF
    _cfg_fbox.mu = _CONTACT_MU

    mb.add_shape_box(
        body=left_finger_body,
        xform=wp.transform(wp.vec3(0.0, 0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox, label="leftfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    mb.add_shape_box(
        body=right_finger_body,
        xform=wp.transform(wp.vec3(0.0, -0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox, label="rightfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    all_ke     = _ARM_KE      + _FINGER_KE
    all_kd     = _ARM_KD      + _FINGER_KD
    all_arm    = _ARM_ARMATURE + _FINGER_ARMATURE
    all_effort = _ARM_EFFORT  + _FINGER_EFFORT
    for i in range(_N_ROBOT_JOINTS):
        mb.joint_target_ke[i]    = float(all_ke[i])
        mb.joint_target_kd[i]    = float(all_kd[i])
        mb.joint_armature[i]     = float(all_arm[i])
        mb.joint_effort_limit[i] = float(all_effort[i])

    for i in range(_N_ROBOT_JOINTS):
        mb.joint_q[i]          = float(_HOME_JOINT_Q[i])
        mb.joint_target_pos[i] = float(_HOME_JOINT_Q[i])

    return mb, hand_local_idx, mb.body_count


def build_batched_model(robot_builder: newton.ModelBuilder, num_worlds: int) -> tuple:
    cfg_cube = newton.ModelBuilder.ShapeConfig()
    cfg_cube.density = _CUBE_DENSITY
    cfg_cube.ke      = _CONTACT_KE
    cfg_cube.kd      = _CONTACT_KD
    cfg_cube.kf      = _CONTACT_KF
    cfg_cube.mu      = _CONTACT_MU

    scene = newton.ModelBuilder()
    for _ in range(num_worlds):
        scene.begin_world()
        scene.add_builder(robot_builder)
        cube_body = scene.add_body(
            xform=wp.transform(wp.vec3(0.0, 0.0, _CUBE_HALF_SIZE), wp.quat_identity()),
            mass=0.0, label="cube",
        )
        scene.add_shape_box(
            body=cube_body,
            hx=_CUBE_HALF_SIZE, hy=_CUBE_HALF_SIZE, hz=_CUBE_HALF_SIZE,
            cfg=cfg_cube, label="cube_shape",
        )
        scene.shape_collision_group[len(scene.shape_body) - 1] = 1
        scene.end_world()

    scene.add_ground_plane()
    batched_model = scene.finalize()

    solver = newton.solvers.SolverMuJoCo(
        batched_model,
        solver="newton",
        integrator="implicitfast",
        iterations=20,
        ls_parallel=True,
        ls_iterations=100,
        nconmax=512 * num_worlds,
        njmax=1000 * num_worlds,
        cone="elliptic",
        impratio=1000.0,
    )
    return batched_model, solver


def reset_batch_state(batched_model, state_0, state_1, cube_positions_np, default_robot_q, num_worlds):
    n_coord = batched_model.joint_coord_count // num_worlds
    joint_q  = np.zeros(batched_model.joint_coord_count, dtype=np.float32)
    joint_qd = np.zeros(batched_model.joint_dof_count,   dtype=np.float32)
    for w in range(num_worlds):
        base = w * n_coord
        joint_q[base : base + _N_ROBOT_JOINTS] = default_robot_q
        cx, cy, cz = cube_positions_np[w]
        joint_q[base + _N_ROBOT_JOINTS     : base + _N_ROBOT_JOINTS + 3] = [cx, cy, cz]
        joint_q[base + _N_ROBOT_JOINTS + 3 : base + _N_ROBOT_JOINTS + 7] = [0., 0., 0., 1.]
    state_0.joint_q.assign(joint_q)
    state_0.joint_qd.assign(joint_qd)
    state_1.joint_q.assign(joint_q)
    state_1.joint_qd.assign(joint_qd)


def _simulate(solver, state_0, state_1, control, contacts, sub_dt, n_substeps):
    for _ in range(n_substeps):
        state_0.clear_forces()
        solver.step(state_0, state_1, control, contacts, sub_dt)
        state_0, state_1 = state_1, state_0


# ---------------------------------------------------------------------------
# Reachability helper (matches reward_utils.reachable_mask logic)
# ---------------------------------------------------------------------------

def _reachable_mask(cube_pos_np, robot_pos_np, r_min, r_max):
    """Per-world reachability mask — (N,) float32, 1.0=reachable."""
    diff = cube_pos_np[:, :2] - robot_pos_np[:, :2]
    dist = np.linalg.norm(diff, axis=1)
    return ((dist >= r_min) & (dist <= r_max)).astype(np.float32)


# ---------------------------------------------------------------------------
# Batch observation extraction
# ---------------------------------------------------------------------------

def run_batch_obs(
    batched_model,
    solver,
    hand_local_idx: int,
    cube_local_idx: int,
    num_bodies_per_world: int,
    num_worlds: int,
    state_0,
    state_1,
    control,
    batch_seqs: list,
    active_count: int,
    cfg: dict,
) -> list:
    """Run active_count sequences simultaneously; return per-sequence obs frame lists."""
    n_coord_per_world = batched_model.joint_coord_count // num_worlds
    n_dof_per_world   = batched_model.joint_dof_count   // num_worlds
    n_ctrl_per_world  = len(control.joint_target_pos)   // num_worlds
    n_frames = len(batch_seqs[0]["frames"])

    r_min = cfg["reachable_radius_min"]
    r_max = cfg["reachable_radius_max"]

    robot_pos_np = np.zeros((num_worlds, 3), dtype=np.float32)  # robot fixed at origin
    default_robot_q = np.array(_HOME_JOINT_Q, dtype=np.float32)

    # Per-world frame accumulator: list of lists (n_frames obs vectors per world)
    frame_obs_pw = [[] for _ in range(num_worlds)]

    contacts = None
    try:
        contacts = batched_model.collide(state_0)
    except AttributeError:
        if hasattr(batched_model, "collider"):
            contacts = batched_model.collider()

    for frame_idx in range(n_frames):
        # --- Apply recorded joint commands ---
        ctrl_np = np.zeros((num_worlds, n_ctrl_per_world), dtype=np.float32)
        for w in range(num_worlds):
            ctrl_np[w, :_N_ROBOT_JOINTS] = batch_seqs[w]["frames"][frame_idx]["joint_pos_cmd"]
        control.joint_target_pos.assign(ctrl_np.reshape(-1))

        # --- Step physics ---
        try:
            contacts = batched_model.collide(state_0)
        except AttributeError:
            pass
        _simulate(solver, state_0, state_1, control, contacts, _SUB_DT, _N_SUBSTEPS_PER_FRAME)

        # --- FK to populate body_q and body_qd ---
        newton.eval_fk(batched_model, state_0.joint_q, state_0.joint_qd, state_0)

        # --- One GPU→CPU sync for all state arrays ---
        body_q_np  = state_0.body_q.numpy()   # (n_bodies_total, 7): [px,py,pz, qx,qy,qz,qw]
        body_qd_np = state_0.body_qd.numpy()  # (n_bodies_total, 6): [omega_xyz, linvel_xyz]
        joint_q_np = state_0.joint_q.numpy()  # (n_coord_total,)
        joint_qd_np= state_0.joint_qd.numpy() # (n_dof_total,)

        # --- Extract per-world observations ---
        for w in range(num_worlds):
            gh   = w * num_bodies_per_world + hand_local_idx   # global body index: EE
            gc   = w * num_bodies_per_world + cube_local_idx   # global body index: cube

            # Cube state
            cube_pos_w  = body_q_np[gh if False else gc][:3]   # (3) position
            cube_quat_w = body_q_np[gc][3:7]                    # (4) [qx,qy,qz,qw]

            # EE state
            ee_pos_w  = body_q_np[gh][:3]   # (3)
            ee_quat_w = body_q_np[gh][3:7]  # (4) [qx,qy,qz,qw]
            # body_qd: [omega_x, omega_y, omega_z, vx, vy, vz] — world frame at CoM
            ee_angvel_w = body_qd_np[gh][0:3]  # (3) [rad/s]
            ee_linvel_w = body_qd_np[gh][3:6]  # (3) [m/s]

            # Joint state (robot DOF only — first _N_ROBOT_JOINTS of each world's slice)
            q_base  = w * n_coord_per_world
            qd_base = w * n_dof_per_world
            joint_pos = joint_q_np [q_base  : q_base  + _N_ROBOT_JOINTS]   # (9)
            joint_vel = joint_qd_np[qd_base : qd_base + _N_ROBOT_JOINTS]   # (9)

            # Last action = current step's joint_pos_cmd (proxy for RL last_action)
            last_action = ctrl_np[w, :_N_ROBOT_JOINTS]   # (9)

            # Robot root frame == world frame (robot fixed at origin)
            # cube_pos_b = cube_pos_w - robot_pos_w
            robot_pos_w = robot_pos_np[w]
            cube_pos_b  = cube_pos_w - robot_pos_w
            ee_pos_b    = ee_pos_w   - robot_pos_w

            # Reachability mask
            cube_dist_xy = float(np.linalg.norm(cube_pos_b[:2]))
            reach_mask   = 1.0 if (r_min <= cube_dist_xy <= r_max) else 0.0

            # Assemble 47-dim obs
            obs = np.concatenate([
                cube_pos_b,    # 3
                cube_quat_w,   # 4
                ee_pos_b,      # 3
                ee_quat_w,     # 4
                ee_linvel_w,   # 3
                ee_angvel_w,   # 3
                joint_pos,     # 9
                joint_vel,     # 9
                last_action,   # 9
            ]).astype(np.float32)   # (47,)

            assert len(obs) == 47

            frame_rec = batch_seqs[w]["frames"][frame_idx]
            frame_obs_pw[w].append({
                "step":          frame_rec["step"],
                "t":             frame_rec["t"],
                "obs":           obs.tolist(),
                "reachable_mask": reach_mask,
            })

    # Build result dicts for active worlds only
    results = []
    for w in range(active_count):
        results.append({
            "id":                    batch_seqs[w]["id"],
            "label":                 batch_seqs[w]["label"],
            "cube_init_pos_w":       batch_seqs[w]["cube_init_pos_w"],
            "cube_horizontal_dist":  batch_seqs[w]["cube_horizontal_dist"],
            "frames":                frame_obs_pw[w],
        })
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Compute full 47-dim RL obs from scripted sequences (batched Newton)."
    )
    parser.add_argument("--input",      type=str,
                        default=str(_OUTPUTS_DIR / "reference_ik_sequences.json"),
                        help="Path to reference_ik_sequences.json (Tool 1 output).")
    parser.add_argument("--output",     type=str,
                        default=str(_OUTPUTS_DIR / "reference_ik_observations.json"),
                        help="Output path for observations JSON.")
    parser.add_argument("--num-worlds", type=int, default=16,
                        help="Batch size (default: 16).")
    parser.add_argument("--sequence_id", type=str, default=None,
                        help="If set, compute observations for this sequence only.")
    args = parser.parse_args()

    urdf_path = _find_panda_urdf()
    print(f"[obs-compute] Panda URDF: {urdf_path}")

    print(f"[obs-compute] Building batched model (num_worlds={args.num_worlds}) ...")
    robot_mb, hand_local_idx, robot_body_count = build_robot_builder(urdf_path)
    batched_model, solver = build_batched_model(robot_mb, args.num_worlds)

    num_bodies_per_world = batched_model.body_count // args.num_worlds
    cube_local_idx       = robot_body_count
    n_coord_per_world    = batched_model.joint_coord_count // args.num_worlds
    n_dof_per_world      = batched_model.joint_dof_count   // args.num_worlds

    print(f"[obs-compute] {batched_model.body_count} bodies total  "
          f"({num_bodies_per_world}/world)  "
          f"{n_coord_per_world} coords/world  {n_dof_per_world} DOFs/world")
    print(f"[obs-compute] hand_local_idx={hand_local_idx}  cube_local_idx={cube_local_idx}")
    print(f"[obs-compute] obs_dims={len(OBS_NAMES)}: {OBS_NAMES}")

    data      = load_sequences(args.input)
    cfg       = data["config"]
    sequences = data["sequences"]

    if args.sequence_id is not None:
        sequences = [s for s in sequences if s["id"] == args.sequence_id]
        if not sequences:
            raise ValueError(f"Sequence '{args.sequence_id}' not found.")
        args.num_worlds = 1
        batched_model, solver = build_batched_model(robot_mb, 1)
        num_bodies_per_world  = batched_model.body_count
        cube_local_idx        = robot_body_count
        print(f"[obs-compute] Single-sequence mode (num_worlds=1)")

    num_worlds = args.num_worlds
    state_0    = batched_model.state()
    state_1    = batched_model.state()
    control    = batched_model.control()

    default_robot_q = np.array(_HOME_JOINT_Q, dtype=np.float32)

    n_seq    = len(sequences)
    n_frames = len(sequences[0]["frames"])
    n_batch  = (n_seq + num_worlds - 1) // num_worlds

    print(f"[obs-compute] {n_seq} sequences × {n_frames} frames | "
          f"batches={n_batch}  substeps={_N_SUBSTEPS_PER_FRAME}×{_SUB_DT*1000:.1f}ms/frame")

    all_results = []
    seq_idx = 0

    for batch_num in range(n_batch):
        active_count = min(num_worlds, n_seq - seq_idx)
        pad_count    = num_worlds - active_count
        batch_seqs   = sequences[seq_idx : seq_idx + active_count]
        if pad_count > 0:
            batch_seqs = batch_seqs + [batch_seqs[0]] * pad_count

        desc = " | ".join(
            f"{s['id']}({label_description(s['label'])})"
            for s in batch_seqs[:active_count]
        )
        print(f"[obs-compute] batch {batch_num + 1}/{n_batch} "
              f"({active_count} active, {pad_count} pad): {desc}", flush=True)

        cube_positions = np.array([s["cube_init_pos_w"] for s in batch_seqs], dtype=np.float32)
        reset_batch_state(batched_model, state_0, state_1, cube_positions, default_robot_q, num_worlds)
        newton.eval_fk(batched_model, state_0.joint_q, state_0.joint_qd, state_0)

        batch_results = run_batch_obs(
            batched_model=batched_model,
            solver=solver,
            hand_local_idx=hand_local_idx,
            cube_local_idx=cube_local_idx,
            num_bodies_per_world=num_bodies_per_world,
            num_worlds=num_worlds,
            state_0=state_0,
            state_1=state_1,
            control=control,
            batch_seqs=batch_seqs,
            active_count=active_count,
            cfg=cfg,
        )

        all_results.extend(batch_results)
        seq_idx += active_count

    output = {
        "version":       "1.0",
        "computed_at":   datetime.datetime.now().isoformat(),
        "source":        args.input,
        "config":        cfg,
        "obs_names":     OBS_NAMES,
        "obs_dims":      len(OBS_NAMES),
        "quat_convention":      "xyzw (Newton/MuJoCo convention)",
        "body_qd_convention":   "[omega_xyz(3), linvel_xyz(3)] world frame at CoM",
        "sequences":     all_results,
    }

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    import json
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"[obs-compute] Saved {n_seq} sequences → {out_path}")


if __name__ == "__main__":
    main()
