"""Tool 2 — Sequence Replayer (Newton physics).

Replays sequences generated by generate_sequences.py, driving a fresh Newton
physics model with the recorded joint_pos_cmd targets, then computing per-frame
rewards and writing them to a JSON output file.

Architecture
------------
Runs fully standalone using Newton physics — no Isaac Sim / AppLauncher required.

Uses the same two-model architecture as the generator, but only the physics
model (robot + cube, 16 DOF) is needed — no IK model required.

For each sequence:
  - Robot is reset to home pose; cube is reset to seq["cube_init_pos_w"].
  - Per frame, control.joint_target_pos is set to the stored joint_pos_cmd
    (padded to 16 elements; cube free-joint DOFs have ke=0 so they're ignored).
  - SUBSTEPS_PER_FRAME=2 physics steps per frame to match generator timing.
  - Cube position is read from phys state body_q[cube_body_idx] (real physics).
  - Rewards are computed via reward_eval.compute_all_rewards.

Variance metric
---------------
Per-sequence, the mean absolute difference between the generator's recorded
joint_pos and this replay's joint_pos is stored as joint_pos_variance_mean.
A high value indicates physics non-determinism or model mismatch.

Success detection
-----------------
  reachable sequence:   cube_pos_z > lift_height
  unreachable sequence: ee_dist_to_signal < 0.15
  success_frame = first frame index where condition met, or -1 if never.

Usage
-----
python replay_sequences.py \\
    --input  data/validation/sequences.json \\
    --output data/validation/replay.json \\
    [--sequence_id seq_0003]   # replay a single sequence (default: all)
"""

import argparse
import datetime
import json
import sys
from pathlib import Path

import numpy as np
import torch
import warp as wp

import newton

sys.path.insert(0, str(Path(__file__).parent))
from _common.reward_eval import REWARD_WEIGHTS, compute_all_rewards
from _common.sequence_schema import (
    expected_high_reward,
    label_description,
    load_sequences,
    save_replay,
)
from _common.waypoint_ik import T_GRIP


_TASK_ROOT   = Path(__file__).parent.parent
_OUTPUTS_DIR = _TASK_ROOT / "data" / "validation"

# ---------------------------------------------------------------------------
# Panda URDF (same candidate list as generator)
# ---------------------------------------------------------------------------

_FRANKA_URDF_CANDIDATES = [
    Path(
        "/home/horde/micromamba/envs/env_isaaclab/lib/python3.11/site-packages/"
        "isaacsim/exts/isaacsim.asset.importer.urdf/data/urdf/robots/"
        "franka_description/robots/panda_arm_hand.urdf"
    ),
]

_PANDA_HAND_BODY_LABEL = "panda/panda_hand"

# PD gains — must match generator exactly
_ARM_KE    = [600, 600, 600, 600, 250, 150, 50]
_ARM_KD    = [50,  50,  50,  50,  30,  25,  15]
_FINGER_KE = [200, 200]  # must match generator exactly
_FINGER_KD = [20,  20]   # must match generator exactly

# Robot joint count (must match generator)
_N_ROBOT_JOINTS = 9

# Cube rigid body properties (must match generator exactly)
_CUBE_HALF_SIZE  = 0.025
_CUBE_DENSITY    = 1000.0   # kg/m³ → mass = 1000 × 0.05³ = 0.125 kg
_CUBE_MASS       = _CUBE_DENSITY * (2 * 0.025) ** 3   # 0.125 kg
_CUBE_FRICTION   = 2.0      # Coulomb friction coeff for cube shape
_FINGER_FRICTION = 2.0      # Friction on finger BOX (must match generator)
_CUBE_CONTACT_KE = 10000.0  # contact stiffness [N/m]

# Finger BOX contact stiffness — must match generator (soft contacts prevent
# lateral impulses from IK drift knocking the cube during lift)
_FINGER_BOX_KE = 500.0
_FINGER_BOX_KD = 5.0



def _find_panda_urdf() -> Path:
    for p in _FRANKA_URDF_CANDIDATES:
        if p.exists():
            return p
    raise FileNotFoundError(
        "Panda URDF not found. Install Isaac Sim pip package or set PANDA_URDF env var."
    )


# ---------------------------------------------------------------------------
# Newton physics setup — robot + cube (same as generator phys_model)
# ---------------------------------------------------------------------------


def build_phys_model(urdf_path: Path):
    """Build Newton physics model (robot + cube) for replay.

    Mirrors generator's phys_model setup exactly so PD dynamics and contacts match.

    Returns:
        phys_model:     finalized Newton Model (robot + cube, 16 DOF)
        hand_idx:       body index of panda_hand
        cube_body_idx:  body index of cube
        solver:         Newton solver (MuJoCo preferred)
    """
    mb = newton.ModelBuilder()
    mb.add_ground_plane()
    mb.add_urdf(str(urdf_path), floating=False)

    # Collision group assignment — must mirror generator exactly.
    # Newton/MuJoCo: shapes collide IFF same group.
    #   group 1 (default): ground + finger BOX shapes + cube → mutual contact
    #   group 2:           arm/hand shapes + finger MESH shapes → isolated
    # NOTE: mujoco_warp does NOT support MESH-BOX contact; explicit BOX finger
    # shapes in group 1 are needed for finger-cube contact detection.
    _left_finger_body  = next(i for i, lbl in enumerate(mb.body_label) if "leftfinger"  in lbl)
    _right_finger_body = next(i for i, lbl in enumerate(mb.body_label) if "rightfinger" in lbl)

    _n_urdf_shapes = len(mb.shape_body)
    for _i in range(_n_urdf_shapes):
        _b = mb.shape_body[_i]
        if _b < 0:
            pass  # ground: keep group 1
        else:
            mb.shape_collision_group[_i] = 2  # arm, hand, finger MESH shapes: group 2

    # Add explicit BOX collision shapes for each finger body (group 1).
    # Geometry must match generator exactly — SQUEEZE mode, wide-coverage variant.
    # local_Z=0.027, hz=0.018, hx=0.025. See generator comments for full analysis.
    # Z_pen ≈ 41mm > Y_pen ≈ 15mm → SAT picks Y (squeeze). Wide hx prevents cube escape.
    _cfg_fbox = newton.ModelBuilder.ShapeConfig()
    _cfg_fbox.ke = _FINGER_BOX_KE
    _cfg_fbox.kd = _FINGER_BOX_KD
    _cfg_fbox.mu = _FINGER_FRICTION

    mb.add_shape_box(
        body=_left_finger_body,
        xform=wp.transform(wp.vec3(0.0, 0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox,
        label="leftfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    mb.add_shape_box(
        body=_right_finger_body,
        xform=wp.transform(wp.vec3(0.0, -0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox,
        label="rightfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    # PD gains
    for i, (ke, kd) in enumerate(zip(_ARM_KE + _FINGER_KE, _ARM_KD + _FINGER_KD)):
        mb.joint_target_ke[i] = float(ke)
        mb.joint_target_kd[i] = float(kd)

    hand_idx = next(
        i for i, l in enumerate(mb.body_label) if _PANDA_HAND_BODY_LABEL in l
    )

    # Cube as free-floating rigid body — must match generator exactly.
    # add_body() implicitly adds a free joint (7 DOF). Do NOT call add_joint_free.
    cube_body_idx = mb.add_body(mass=0.0, label="cube")
    cfg_cube = newton.ModelBuilder.ShapeConfig()
    cfg_cube.density = _CUBE_DENSITY
    cfg_cube.mu      = _CUBE_FRICTION
    cfg_cube.ke      = _CUBE_CONTACT_KE
    mb.add_shape_box(
        body=cube_body_idx,
        hx=_CUBE_HALF_SIZE, hy=_CUBE_HALF_SIZE, hz=_CUBE_HALF_SIZE,
        cfg=cfg_cube,
        label="cube_shape",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    phys_model = mb.finalize()

    try:
        solver = newton.solvers.SolverMuJoCo(phys_model, njmax=256)
    except Exception:
        solver = newton.solvers.SolverFeatherstone(phys_model)

    return phys_model, hand_idx, cube_body_idx, solver


# ---------------------------------------------------------------------------
# Replay one sequence
# ---------------------------------------------------------------------------


def replay_sequence(
    phys_model,
    hand_idx: int,
    cube_body_idx: int,
    solver,
    seq: dict,
    cfg: dict,
    device: torch.device,
    dt: float = 0.02,
) -> dict:
    """Replay a single sequence using Newton physics. Returns replay result dict.

    The cube is fully physics-simulated throughout; grasping relies on friction contacts
    between the finger BOX shapes and the cube.

    Args:
        phys_model:     Newton Model with robot + cube (16 DOF).
        hand_idx:       body index of panda_hand.
        cube_body_idx:  body index of cube in phys_model.
        solver:         Newton solver for phys_model.
        seq:            sequence dict from load_sequences().
        cfg:            geometry config dict.
        device:         torch device for reward tensors.
        dt:             physics timestep [s] — must match generator.
    """
    cx, cy, cz = seq["cube_init_pos_w"]

    success_pos = torch.tensor(cfg["success_ee_position"], device=device, dtype=torch.float32).unsqueeze(0)
    signal_pos  = torch.tensor(cfg["signal_ee_position"],  device=device, dtype=torch.float32).unsqueeze(0)
    robot_pos_w = torch.zeros(1, 3, device=device)

    r_min        = cfg["reachable_radius_min"]
    r_max        = cfg["reachable_radius_max"]
    lift_height  = cfg["lift_height"]
    is_reachable = seq["label"]["reachable"]
    is_success   = seq["label"]["success"]

    # --- Physics state -------------------------------------------------------
    n_phys = phys_model.joint_coord_count   # 16
    n_dof  = phys_model.joint_dof_count     # 15

    state_0 = phys_model.state()
    state_1 = phys_model.state()
    control = phys_model.control()

    has_collider = hasattr(phys_model, "collider")
    contacts = phys_model.collider() if has_collider else None

    # --- Reset: robot to home, cube to sequence init position ----------------
    default_robot_q = phys_model.joint_q.numpy()[:_N_ROBOT_JOINTS].astype(np.float32)

    joint_q_init = np.zeros(n_phys, dtype=np.float32)
    joint_q_init[:_N_ROBOT_JOINTS] = default_robot_q
    joint_q_init[_N_ROBOT_JOINTS:_N_ROBOT_JOINTS + 3] = [cx, cy, cz]
    joint_q_init[_N_ROBOT_JOINTS + 3:n_phys]          = [0.0, 0.0, 0.0, 1.0]

    state_0.joint_q.assign(joint_q_init)
    state_0.joint_qd.assign(np.zeros(n_dof, dtype=np.float32))

    episode_rewards = {k: 0.0 for k in list(REWARD_WEIGHTS.keys()) + ["total"]}
    frame_results   = []

    # Generator records every 2 steps → each replay frame = 2 physics substeps
    SUBSTEPS_PER_FRAME = 2

    frames        = seq["frames"]
    success_frame = -1
    variance_accum = []
    prev_robot_q_replay = default_robot_q.copy()
    prev_ee_pos_replay  = None

    cube_pos_arr = np.array([cx, cy, cz], dtype=np.float32)  # live cube position (updated each substep)

    for frame_idx, frame in enumerate(frames):
        # Pad 9-element robot command to 16-element for phys_model
        joint_pos_cmd = np.array(frame["joint_pos_cmd"], dtype=np.float32)
        cmd_full = np.zeros(n_phys, dtype=np.float32)
        cmd_full[:_N_ROBOT_JOINTS] = joint_pos_cmd
        control.joint_target_pos = wp.array(cmd_full, dtype=wp.float32)

        # t for the first substep of this frame: frame["t"] = step * dt where
        # step = frame_idx * SUBSTEPS_PER_FRAME (generator records every 2 steps).
        t_frame = frame["t"]

        body_q = None   # will hold the last body_q after the substep loop
        for substep in range(SUBSTEPS_PER_FRAME):
            state_0.clear_forces()

            if contacts is not None:
                solver.step(state_0, state_1, control, contacts, dt)
            else:
                solver.step(state_0, state_1, control, None, dt)
            state_0, state_1 = state_1, state_0

            # Update live cube position and EE for reward computation.
            newton.eval_fk(phys_model, state_0.joint_q, state_0.joint_qd, state_0)
            body_q       = state_0.body_q.numpy()
            cube_pos_arr = np.array(body_q[cube_body_idx][:3], dtype=np.float32)

        # body_q already up to date from the last substep FK call above
        ee_pos_list  = body_q[hand_idx][:3].tolist()
        cube_pos_now = cube_pos_arr.tolist()

        # Robot joint positions (first 9) and velocity.
        # Frame-to-frame time = SUBSTEPS_PER_FRAME * dt (each frame is 2 physics steps).
        robot_q_replay   = state_0.joint_q.numpy()[:_N_ROBOT_JOINTS].astype(np.float32)
        frame_dt = SUBSTEPS_PER_FRAME * dt
        joint_vel_replay = (robot_q_replay - prev_robot_q_replay) / frame_dt
        prev_ee_pos_replay = ee_pos_list

        # Reward tensors
        ee_pos_w    = torch.tensor(ee_pos_list,          device=device, dtype=torch.float32).unsqueeze(0)
        cube_pos_w  = torch.tensor(cube_pos_now,         device=device, dtype=torch.float32).unsqueeze(0)
        joint_vel   = torch.tensor(joint_vel_replay,     device=device, dtype=torch.float32).unsqueeze(0)
        action_curr = torch.tensor(joint_pos_cmd,        device=device, dtype=torch.float32).unsqueeze(0)
        action_prev = torch.tensor(prev_robot_q_replay,  device=device, dtype=torch.float32).unsqueeze(0)

        rews = compute_all_rewards(
            ee_pos_w=ee_pos_w, cube_pos_w=cube_pos_w, robot_pos_w=robot_pos_w,
            joint_vel=joint_vel, action_curr=action_curr, action_prev=action_prev,
            success_ee_pos=success_pos, signal_ee_pos=signal_pos,
            r_min=r_min, r_max=r_max, lift_height=lift_height,
        )

        frame_rew = {k: float(v[0].item()) for k, v in rews.items()}
        for k in episode_rewards:
            episode_rewards[k] += frame_rew.get(k, 0.0)

        # Success detection
        # reachable: cube lifted above threshold (EE-near-success not checked because
        #   with virtual grasp, EE is at success_pos only after cube drops below threshold)
        if success_frame == -1:
            if is_reachable:
                if cube_pos_now[2] > lift_height:
                    success_frame = frame_idx
            else:
                if float(torch.dist(ee_pos_w, signal_pos).item()) < 0.15:
                    success_frame = frame_idx

        # Variance: compare generator's recorded robot joint_pos vs replay
        gen_robot_q = np.array(frame["joint_pos"], dtype=np.float32)
        variance_accum.append(np.abs(gen_robot_q - robot_q_replay))

        frame_results.append({
            "step":           frame["step"],
            "t":              frame["t"],
            "reachable_mask": frame_rew["reachable_mask"],
            "robot_pos_w":    [0.0, 0.0, 0.0],
            "ee_pos_w":       ee_pos_list,
            "cube_pos_w":     cube_pos_now,
            "rewards":        {k: round(frame_rew[k], 6) for k in REWARD_WEIGHTS},
        })

        prev_robot_q_replay = robot_q_replay

    joint_pos_variance_mean = float(np.mean(np.stack(variance_accum))) if variance_accum else 0.0

    return {
        "id":                      seq["id"],
        "label":                   seq["label"],
        "expected_high_reward":    expected_high_reward(seq["label"]),
        "episode_rewards":         {k: round(v, 4) for k, v in episode_rewards.items()},
        "success_frame":           success_frame,
        "joint_pos_variance_mean": round(joint_pos_variance_mean, 6),
        "frames":                  frame_results,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Replay Franka cube pick sequences with Newton physics and compute rewards."
    )
    parser.add_argument("--input",       type=str, default=str(_OUTPUTS_DIR / "sequences.json"),
                        help="Path to sequences.json (Tool 1 output).")
    parser.add_argument("--output",      type=str, default=str(_OUTPUTS_DIR / "replay.json"),
                        help="Path for replay output JSON.")
    parser.add_argument("--sequence_id", type=str, default=None,
                        help="If set, replay only this sequence ID. Otherwise replays all.")
    parser.add_argument("--device",      type=str, default="cpu",
                        help="Torch device for reward tensors (cpu/cuda).")
    args = parser.parse_args()

    device = torch.device(args.device)

    urdf_path = _find_panda_urdf()
    print(f"[replay] Loading Panda URDF: {urdf_path}")
    phys_model, hand_idx, cube_body_idx, solver = build_phys_model(urdf_path)
    print(f"[replay] Newton model: {phys_model.body_count} bodies, {phys_model.joint_coord_count} joint coords")
    print(f"[replay] Solver: {type(solver).__name__}")

    data = load_sequences(args.input)
    cfg  = data["config"]

    sequences = data["sequences"]
    if args.sequence_id is not None:
        sequences = [s for s in sequences if s["id"] == args.sequence_id]
        if not sequences:
            raise ValueError(f"Sequence '{args.sequence_id}' not found in {args.input}")

    results = []
    for i, seq in enumerate(sequences):
        lbl_str = label_description(seq["label"])
        print(f"[replay] {i + 1}/{len(sequences)} — {seq['id']} ({lbl_str})", end="", flush=True)
        result = replay_sequence(phys_model, hand_idx, cube_body_idx, solver, seq, cfg, device)
        results.append(result)

        ep_total  = result["episode_rewards"]["total"]
        expected  = "HIGH" if result["expected_high_reward"] else "LOW"
        actual    = "HIGH" if ep_total > 10.0 else "LOW"
        status    = "OK" if actual == expected else "MISMATCH"
        sf        = result["success_frame"]
        variance  = result["joint_pos_variance_mean"]
        print(f"  episode_reward={ep_total:+.1f}  expected={expected}  [{status}]"
              f"  success_frame={sf}  variance={variance:.4f}")

    output = {
        "version":     "1.0",
        "replayed_at": datetime.datetime.now().isoformat(),
        "source":      args.input,
        "config":      cfg,
        "sequences":   results,
    }
    save_replay(output, args.output)


if __name__ == "__main__":
    main()
