"""Tool 2 — Sequence Replayer (batched multi-world Newton FK + full physics).

Replays sequences generated by generate_sequences.py, driving a fresh Newton
physics model with the recorded joint_pos_cmd targets, then computing per-frame
rewards and writing them to a JSON output file.

Architecture
------------
Runs N worlds simultaneously via begin_world/add_builder/end_world, mirroring
generate_sequences.py. All N sequences are stepped in a single solver.step() call
per substep — the same GPU parallelism as the generator.

Robot motion: PD controller tracks the recorded joint_pos_cmd targets.
  FK-equivalent: same commands → same physics → same cube trajectory.

Cube physics: full Newton physics simulation — gravity, contact forces, friction.
  No analytic cube teleportation or kinematic overrides.

Physics model mirrors the generator's phys_model exactly:
  - Same PD gains, armature, effort limits
  - Same gravity compensation (mujoco:jnt_actgravcomp + mujoco:gravcomp)
  - Same finger BOX shapes + collision groups
  - Same contact parameters (ke, kd, kf, mu)
  - Same solver (SolverMuJoCo, impratio=1000, cone=elliptic)
  - Same substep count: 10 × 2ms per recorded frame
    (generator: 10 substeps per outer step × record_every=1 = 10 substeps/frame)

Batch processing
----------------
The outer loop processes sequences in batches of --num-worlds (default 16).
Each batch:
  1. Reset all N worlds: robot → _HOME_JOINT_Q, cubes → their init positions.
  2. For each of the 500 recorded frames:
       a. Set control commands from each world's recorded joint_pos_cmd.
       b. Run 10 physics substeps (one solver.step per substep, all N worlds).
       c. Read body_q / joint_q for all N worlds in one GPU→CPU sync.
       d. Compute rewards for all N worlds in one vectorized torch call.
  3. Collect per-world results.
Last batch is zero-padded if num_sequences % num_worlds != 0.

Usage
-----
python replay_sequences.py \\
    --input  data/validation/sequences.json \\
    --output data/validation/replay.json \\
    [--num-worlds 16]          # batch size (default: 16)
    [--sequence_id seq_0003]   # replay a single sequence (default: all)
"""

import argparse
import datetime
import sys
from pathlib import Path

import numpy as np
import torch
import warp as wp

import newton

sys.path.insert(0, str(Path(__file__).parent))
from _common.reward_eval import REWARD_WEIGHTS, compute_all_rewards
from _common.sequence_schema import (
    expected_high_reward,
    label_description,
    load_sequences,
    save_replay,
)


_TASK_ROOT   = Path(__file__).parent.parent
_OUTPUTS_DIR = _TASK_ROOT / "data" / "validation"

# ---------------------------------------------------------------------------
# Panda URDF (same candidate list as generator)
# ---------------------------------------------------------------------------

_FRANKA_URDF_CANDIDATES = [
    Path(
        "/home/horde/micromamba/envs/env_isaaclab/lib/python3.11/site-packages/"
        "isaacsim/exts/isaacsim.asset.importer.urdf/data/urdf/robots/"
        "franka_description/robots/panda_arm_hand.urdf"
    ),
]

_PANDA_HAND_BODY_LABEL = "panda_hand"   # substring match against mb.body_label entries

# ---------------------------------------------------------------------------
# Physics constants — MUST match generate_sequences.py exactly
# ---------------------------------------------------------------------------

_ARM_KE          = [4500, 4500, 3500, 3500, 2000, 2000, 2000]
_ARM_KD          = [450,  450,  350,  350,  200,  200,  200]
_FINGER_KE       = [100,  100]
_FINGER_KD       = [10,   10]
_ARM_ARMATURE    = [0.30, 0.30, 0.30, 0.30, 0.11, 0.11, 0.11]
_FINGER_ARMATURE = [0.15, 0.15]
_ARM_EFFORT      = [87.0, 87.0, 87.0, 87.0, 12.0, 12.0, 12.0]
_FINGER_EFFORT   = [100.0, 100.0]

_CONTACT_KE  = 5.0e4
_CONTACT_KD  = 5.0e2
_CONTACT_KF  = 1.0e3
_CONTACT_MU  = 0.75

_N_ROBOT_JOINTS = 9    # 7 arm + 2 finger joints

# Initial "ready" pose — MUST match generate_sequences.py exactly.
# All-zero joints put EE at [0.088, 0, 0.926], 13cm off workspace.
_HOME_JOINT_Q = [
    -3.6802115e-03,   # joint1
     2.3901723e-02,   # joint2
     3.6804110e-03,   # joint3
    -2.3683236e+00,   # joint4  (elbow bent ~136°)
    -1.2918962e-04,   # joint5
     2.3922248e+00,   # joint6  (~137°, wrist-up)
     7.8549200e-01,   # joint7  (45°)
     0.04,            # finger1 open (4 cm per finger)
     0.04,            # finger2 open
]

_CUBE_HALF_SIZE = 0.025
_CUBE_DENSITY   = 400.0   # kg/m³

# Substeps per recorded frame (must be EVEN so state_0 holds result after the loop).
# Generator: 10 substeps per outer step × record_every=1 outer step = 10 substeps.
_N_SUBSTEPS_PER_FRAME = 10
_SUB_DT               = 0.002   # 2ms per substep → 20ms per recorded frame


def _find_panda_urdf() -> Path:
    for p in _FRANKA_URDF_CANDIDATES:
        if p.exists():
            return p
    raise FileNotFoundError(
        "Panda URDF not found. Install Isaac Sim pip package or set PANDA_URDF env var."
    )


# ---------------------------------------------------------------------------
# Model building — mirrors generate_sequences.py exactly
# ---------------------------------------------------------------------------


def build_robot_builder(urdf_path: Path) -> tuple:
    """Build unfinalized robot-only ModelBuilder for N-world tiling.

    Identical to generate_sequences.build_robot_builder: URDF + PD gains +
    gravity compensation + finger BOX shapes + HOME_JOINT_Q init.
    No ground plane, no cube (added at scene / per-world level).

    Returns:
        robot_mb:         unfinalized ModelBuilder
        hand_local_idx:   body index of panda_hand within this builder
        robot_body_count: number of bodies (= cube's local body offset after tiling)
    """
    mb = newton.ModelBuilder()
    newton.solvers.SolverMuJoCo.register_custom_attributes(mb)
    mb.add_urdf(str(urdf_path), floating=False, enable_self_collisions=False,
                parse_visuals_as_colliders=False)

    hand_local_idx    = next(i for i, k in enumerate(mb.body_label) if _PANDA_HAND_BODY_LABEL in k)
    left_finger_body  = next(i for i, k in enumerate(mb.body_label) if "leftfinger"  in k)
    right_finger_body = next(i for i, k in enumerate(mb.body_label) if "rightfinger" in k)

    # ---- Gravity compensation ------------------------------------------------
    gravcomp_dof = mb.custom_attributes["mujoco:jnt_actgravcomp"]
    if gravcomp_dof.values is None:
        gravcomp_dof.values = {}
    for dof_idx in range(7):
        gravcomp_dof.values[dof_idx] = True

    gravcomp_body = mb.custom_attributes["mujoco:gravcomp"]
    if gravcomp_body.values is None:
        gravcomp_body.values = {}
    for body_idx in range(2, mb.body_count):
        gravcomp_body.values[body_idx] = 1.0

    # ---- Collision groups: URDF mesh shapes → group 2 ----------------------
    for i in range(len(mb.shape_body)):
        if mb.shape_body[i] >= 0:
            mb.shape_collision_group[i] = 2

    # ---- Finger BOX shapes — group 1 for BOX-BOX contact with cube ----------
    _cfg_fbox = newton.ModelBuilder.ShapeConfig()
    _cfg_fbox.ke = _CONTACT_KE
    _cfg_fbox.kd = _CONTACT_KD
    _cfg_fbox.kf = _CONTACT_KF
    _cfg_fbox.mu = _CONTACT_MU

    mb.add_shape_box(
        body=left_finger_body,
        xform=wp.transform(wp.vec3(0.0, 0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox, label="leftfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    mb.add_shape_box(
        body=right_finger_body,
        xform=wp.transform(wp.vec3(0.0, -0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox, label="rightfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    # ---- PD gains + armature + effort limits --------------------------------
    all_ke     = _ARM_KE      + _FINGER_KE
    all_kd     = _ARM_KD      + _FINGER_KD
    all_arm    = _ARM_ARMATURE + _FINGER_ARMATURE
    all_effort = _ARM_EFFORT  + _FINGER_EFFORT
    for i in range(_N_ROBOT_JOINTS):
        mb.joint_target_ke[i]    = float(all_ke[i])
        mb.joint_target_kd[i]    = float(all_kd[i])
        mb.joint_armature[i]     = float(all_arm[i])
        mb.joint_effort_limit[i] = float(all_effort[i])

    # ---- Initial joint configuration ----------------------------------------
    for i in range(_N_ROBOT_JOINTS):
        mb.joint_q[i]          = float(_HOME_JOINT_Q[i])
        mb.joint_target_pos[i] = float(_HOME_JOINT_Q[i])

    return mb, hand_local_idx, mb.body_count


def build_batched_model(robot_builder: newton.ModelBuilder, num_worlds: int) -> tuple:
    """Tile num_worlds robot+cube environments into one batched Newton model.

    Identical to generate_sequences.build_batched_model.

    Returns:
        batched_model: finalized Newton Model (N × (robot + cube))
        solver:        SolverMuJoCo for batched_model
    """
    cfg_cube = newton.ModelBuilder.ShapeConfig()
    cfg_cube.density = _CUBE_DENSITY
    cfg_cube.ke      = _CONTACT_KE
    cfg_cube.kd      = _CONTACT_KD
    cfg_cube.kf      = _CONTACT_KF
    cfg_cube.mu      = _CONTACT_MU

    scene = newton.ModelBuilder()
    for _ in range(num_worlds):
        scene.begin_world()
        scene.add_builder(robot_builder)
        cube_body = scene.add_body(
            xform=wp.transform(wp.vec3(0.0, 0.0, _CUBE_HALF_SIZE), wp.quat_identity()),
            mass=0.0, label="cube",
        )
        scene.add_shape_box(
            body=cube_body,
            hx=_CUBE_HALF_SIZE, hy=_CUBE_HALF_SIZE, hz=_CUBE_HALF_SIZE,
            cfg=cfg_cube, label="cube_shape",
        )
        scene.shape_collision_group[len(scene.shape_body) - 1] = 1
        scene.end_world()

    scene.add_ground_plane()
    batched_model = scene.finalize()

    solver = newton.solvers.SolverMuJoCo(
        batched_model,
        solver="newton",
        integrator="implicitfast",
        iterations=20,
        ls_parallel=True,
        ls_iterations=100,
        nconmax=512 * num_worlds,
        njmax=1000 * num_worlds,
        cone="elliptic",
        impratio=1000.0,
    )
    return batched_model, solver


# ---------------------------------------------------------------------------
# State reset
# ---------------------------------------------------------------------------


def reset_batch_state(
    batched_model,
    state_0,
    state_1,
    cube_positions_np: np.ndarray,
    default_robot_q: np.ndarray,
    num_worlds: int,
) -> None:
    """Reset all worlds: robot → home pose, cubes → their init positions."""
    n_coord = batched_model.joint_coord_count // num_worlds

    joint_q  = np.zeros(batched_model.joint_coord_count, dtype=np.float32)
    joint_qd = np.zeros(batched_model.joint_dof_count,   dtype=np.float32)

    for w in range(num_worlds):
        base = w * n_coord
        joint_q[base : base + _N_ROBOT_JOINTS] = default_robot_q
        cx, cy, cz = cube_positions_np[w]
        joint_q[base + _N_ROBOT_JOINTS     : base + _N_ROBOT_JOINTS + 3] = [cx, cy, cz]
        joint_q[base + _N_ROBOT_JOINTS + 3 : base + _N_ROBOT_JOINTS + 7] = [0., 0., 0., 1.]

    state_0.joint_q.assign(joint_q)
    state_0.joint_qd.assign(joint_qd)
    state_1.joint_q.assign(joint_q)
    state_1.joint_qd.assign(joint_qd)


# ---------------------------------------------------------------------------
# Physics inner loop
# ---------------------------------------------------------------------------


def _simulate(solver, state_0, state_1, control, contacts, sub_dt, n_substeps):
    """Run n_substeps physics substeps.

    n_substeps MUST be even — with an even count state_0 holds the current
    result after the loop (same guarantee as generate_sequences._simulate).
    """
    for _ in range(n_substeps):
        state_0.clear_forces()
        solver.step(state_0, state_1, control, contacts, sub_dt)
        state_0, state_1 = state_1, state_0


# ---------------------------------------------------------------------------
# Batch replay
# ---------------------------------------------------------------------------


def run_batch_replay(
    batched_model,
    solver,
    hand_local_idx: int,
    cube_local_idx: int,
    num_bodies_per_world: int,
    num_worlds: int,
    state_0,
    state_1,
    control,
    batch_seqs: list,   # len == num_worlds; last batch may be padded
    active_count: int,  # number of real (non-padded) sequences in this batch
    cfg: dict,
    device: torch.device,
) -> list:
    """Replay active_count sequences simultaneously. Returns list of active_count result dicts.

    batch_seqs has exactly num_worlds entries; indices [active_count, num_worlds) are
    padding (clones of the first real sequence) whose results are discarded.
    """
    n_coord_per_world = batched_model.joint_coord_count // num_worlds   # 16
    n_ctrl_per_world  = len(control.joint_target_pos) // num_worlds     # 15

    n_frames    = len(batch_seqs[0]["frames"])
    r_min       = cfg["reachable_radius_min"]
    r_max       = cfg["reachable_radius_max"]
    lift_height = cfg["lift_height"]

    success_pos = torch.tensor(cfg["success_ee_position"], device=device, dtype=torch.float32)
    signal_pos  = torch.tensor(cfg["signal_ee_position"],  device=device, dtype=torch.float32)
    robot_pos_t = torch.zeros(num_worlds, 3, device=device)
    success_pos_t = success_pos.unsqueeze(0).expand(num_worlds, -1)
    signal_pos_t  = signal_pos.unsqueeze(0).expand(num_worlds, -1)

    default_robot_q = np.array(_HOME_JOINT_Q, dtype=np.float32)

    # Per-world accumulators
    episode_rewards     = [{k: 0.0 for k in list(REWARD_WEIGHTS.keys()) + ["total"]}
                           for _ in range(num_worlds)]
    success_frames      = [-1] * num_worlds
    variance_accum      = [[] for _ in range(num_worlds)]
    frame_results_pw    = [[] for _ in range(num_worlds)]
    prev_robot_q        = np.tile(default_robot_q, (num_worlds, 1))

    # Initial contacts
    contacts = None
    try:
        contacts = batched_model.collide(state_0)
    except AttributeError:
        if hasattr(batched_model, "collider"):
            contacts = batched_model.collider()

    for frame_idx in range(n_frames):
        # --- Set joint targets from recorded commands (one write for all N worlds) ---
        ctrl_np = np.zeros((num_worlds, n_ctrl_per_world), dtype=np.float32)
        for w in range(num_worlds):
            ctrl_np[w, :_N_ROBOT_JOINTS] = batch_seqs[w]["frames"][frame_idx]["joint_pos_cmd"]
        control.joint_target_pos.assign(ctrl_np.reshape(-1))

        # --- Refresh contacts then run 20 substeps ---
        try:
            contacts = batched_model.collide(state_0)
        except AttributeError:
            pass
        _simulate(solver, state_0, state_1, control, contacts, _SUB_DT, _N_SUBSTEPS_PER_FRAME)

        # --- Read all-worlds state in one GPU→CPU sync ---
        newton.eval_fk(batched_model, state_0.joint_q, state_0.joint_qd, state_0)
        body_q_np  = state_0.body_q.numpy()
        joint_q_np = state_0.joint_q.numpy()

        # --- Extract per-world observations ---
        ee_pos_np        = np.empty((num_worlds, 3), dtype=np.float32)
        cube_pos_np      = np.empty((num_worlds, 3), dtype=np.float32)
        robot_q_np       = np.empty((num_worlds, _N_ROBOT_JOINTS), dtype=np.float32)

        for w in range(num_worlds):
            gh = w * num_bodies_per_world + hand_local_idx
            gc = w * num_bodies_per_world + cube_local_idx
            ee_pos_np[w]   = body_q_np[gh][:3]
            cube_pos_np[w] = body_q_np[gc][:3]
            base = w * n_coord_per_world
            robot_q_np[w]  = joint_q_np[base : base + _N_ROBOT_JOINTS]

        # gripper_width = finger_joint1 + finger_joint2 (indices 7, 8 in robot_q)
        gripper_width_np = robot_q_np[:, 7] + robot_q_np[:, 8]

        frame_dt        = _N_SUBSTEPS_PER_FRAME * _SUB_DT
        joint_vel_np    = (robot_q_np - prev_robot_q) / frame_dt

        # --- Vectorised reward computation for all N worlds ---
        ee_pos_t         = torch.tensor(ee_pos_np,         device=device, dtype=torch.float32)
        cube_pos_t       = torch.tensor(cube_pos_np,       device=device, dtype=torch.float32)
        gripper_width_t  = torch.tensor(gripper_width_np,  device=device, dtype=torch.float32)
        joint_vel_t      = torch.tensor(joint_vel_np,      device=device, dtype=torch.float32)
        action_curr_t    = torch.tensor(ctrl_np[:, :_N_ROBOT_JOINTS], device=device, dtype=torch.float32)
        action_prev_t    = torch.tensor(prev_robot_q,      device=device, dtype=torch.float32)

        rews = compute_all_rewards(
            ee_pos_w=ee_pos_t, cube_pos_w=cube_pos_t, robot_pos_w=robot_pos_t,
            gripper_width=gripper_width_t,
            joint_vel=joint_vel_t, action_curr=action_curr_t, action_prev=action_prev_t,
            success_ee_pos=success_pos_t, signal_ee_pos=signal_pos_t,
            r_min=r_min, r_max=r_max, lift_height=lift_height,
        )

        # --- Per-world bookkeeping ---
        for w in range(num_worlds):
            frame_rew = {k: float(v[w].item()) for k, v in rews.items()}
            for k in episode_rewards[w]:
                episode_rewards[w][k] += frame_rew.get(k, 0.0)

            if success_frames[w] == -1:
                if batch_seqs[w]["label"]["reachable"]:
                    if cube_pos_np[w][2] > lift_height:
                        success_frames[w] = frame_idx
                else:
                    if float(torch.dist(ee_pos_t[w], signal_pos).item()) < 0.15:
                        success_frames[w] = frame_idx

            gen_robot_q = np.array(batch_seqs[w]["frames"][frame_idx]["joint_pos"], dtype=np.float32)
            variance_accum[w].append(np.abs(gen_robot_q - robot_q_np[w]))

            frame_results_pw[w].append({
                "step":           batch_seqs[w]["frames"][frame_idx]["step"],
                "t":              batch_seqs[w]["frames"][frame_idx]["t"],
                "reachable_mask": frame_rew["reachable_mask"],
                "robot_pos_w":    [0., 0., 0.],
                "ee_pos_w":       ee_pos_np[w].tolist(),
                "cube_pos_w":     cube_pos_np[w].tolist(),
                "rewards":        {k: round(frame_rew[k], 6) for k in REWARD_WEIGHTS},
            })

        prev_robot_q = robot_q_np.copy()

    # --- Build result dicts (active worlds only) ---
    results = []
    for w in range(active_count):
        var_mean = float(np.mean(np.stack(variance_accum[w]))) if variance_accum[w] else 0.0
        results.append({
            "id":                      batch_seqs[w]["id"],
            "label":                   batch_seqs[w]["label"],
            "expected_high_reward":    expected_high_reward(batch_seqs[w]["label"]),
            "episode_rewards":         {k: round(v, 4) for k, v in episode_rewards[w].items()},
            "success_frame":           success_frames[w],
            "joint_pos_variance_mean": round(var_mean, 6),
            "frames":                  frame_results_pw[w],
        })
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Replay Franka cube pick sequences with batched Newton FK + full physics."
    )
    parser.add_argument("--input",       type=str, default=str(_OUTPUTS_DIR / "reference_ik_sequences.json"),
                        help="Path to reference_ik_sequences.json (Tool 1 output).")
    parser.add_argument("--output",      type=str, default=str(_OUTPUTS_DIR / "reference_ik_replay.json"),
                        help="Path for replay output JSON.")
    parser.add_argument("--num-worlds",  type=int, default=16,
                        help="Batch size — number of sequences replayed simultaneously.")
    parser.add_argument("--sequence_id", type=str, default=None,
                        help="If set, replay only this sequence ID (num-worlds ignored).")
    parser.add_argument("--device",      type=str, default="cpu",
                        help="Torch device for reward tensors (cpu/cuda).")
    args = parser.parse_args()

    device = torch.device(args.device)

    urdf_path = _find_panda_urdf()
    print(f"[replay] Panda URDF: {urdf_path}")

    print(f"[replay] Building batched model (num_worlds={args.num_worlds}) ...")
    robot_mb, hand_local_idx, robot_body_count = build_robot_builder(urdf_path)
    batched_model, solver = build_batched_model(robot_mb, args.num_worlds)

    num_bodies_per_world = batched_model.body_count // args.num_worlds
    cube_local_idx       = robot_body_count   # cube added right after robot bodies

    n_coord_per_world = batched_model.joint_coord_count // args.num_worlds
    n_ctrl_per_world  = len(batched_model.control().joint_target_pos) // args.num_worlds
    print(f"[replay] Batched model: {batched_model.body_count} bodies  "
          f"({num_bodies_per_world} per world)  "
          f"{n_coord_per_world} coords/world  {n_ctrl_per_world} ctrl DOFs/world")
    print(f"[replay] hand_local_idx={hand_local_idx}  cube_local_idx={cube_local_idx}")
    print(f"[replay] Solver: {type(solver).__name__}")
    print(f"[replay] Substeps: {_N_SUBSTEPS_PER_FRAME} × {_SUB_DT*1000:.1f}ms = "
          f"{_N_SUBSTEPS_PER_FRAME*_SUB_DT*1000:.0f}ms per frame")

    data      = load_sequences(args.input)
    cfg       = data["config"]
    sequences = data["sequences"]

    if args.sequence_id is not None:
        sequences = [s for s in sequences if s["id"] == args.sequence_id]
        if not sequences:
            raise ValueError(f"Sequence '{args.sequence_id}' not found in {args.input}")
        # Single-sequence path: use num_worlds=1
        args.num_worlds = 1
        batched_model, solver = build_batched_model(robot_mb, 1)
        num_bodies_per_world  = batched_model.body_count
        cube_local_idx        = robot_body_count
        print(f"[replay] Single-sequence mode (num_worlds=1)")

    num_worlds = args.num_worlds
    state_0    = batched_model.state()
    state_1    = batched_model.state()
    control    = batched_model.control()

    default_robot_q = np.array(_HOME_JOINT_Q, dtype=np.float32)

    n_seq    = len(sequences)
    n_frames = len(sequences[0]["frames"])
    n_batch  = (n_seq + num_worlds - 1) // num_worlds

    print(f"[replay] Replaying {n_seq} sequences in batches of {num_worlds} "
          f"| {n_frames} frames × {_N_SUBSTEPS_PER_FRAME*_SUB_DT*1000:.0f}ms = "
          f"{n_frames * _N_SUBSTEPS_PER_FRAME * _SUB_DT:.1f}s per sequence")

    all_results = []
    seq_idx     = 0

    for batch_num in range(n_batch):
        active_count = min(num_worlds, n_seq - seq_idx)
        pad_count    = num_worlds - active_count

        batch_seqs = sequences[seq_idx : seq_idx + active_count]
        if pad_count > 0:
            batch_seqs = batch_seqs + [batch_seqs[0]] * pad_count   # pad with first real seq

        # Header
        desc = " | ".join(
            f"{s['id']}({label_description(s['label'])})"
            for s in batch_seqs[:active_count]
        )
        print(f"[replay] batch {batch_num + 1}/{n_batch} "
              f"({active_count} active, {pad_count} pad): {desc}", flush=True)

        # Reset
        cube_positions = np.array([s["cube_init_pos_w"] for s in batch_seqs], dtype=np.float32)
        reset_batch_state(batched_model, state_0, state_1, cube_positions, default_robot_q, num_worlds)
        newton.eval_fk(batched_model, state_0.joint_q, state_0.joint_qd, state_0)

        # Run batch
        batch_results = run_batch_replay(
            batched_model=batched_model,
            solver=solver,
            hand_local_idx=hand_local_idx,
            cube_local_idx=cube_local_idx,
            num_bodies_per_world=num_bodies_per_world,
            num_worlds=num_worlds,
            state_0=state_0,
            state_1=state_1,
            control=control,
            batch_seqs=batch_seqs,
            active_count=active_count,
            cfg=cfg,
            device=device,
        )

        # Print per-sequence summary
        for w, result in enumerate(batch_results):
            ep_total = result["episode_rewards"]["total"]
            expected = "SUCCESS" if result["expected_high_reward"] else "FAILURE"
            actual   = "SUCCESS" if result["success_frame"] >= 0 else "FAILURE"
            status   = "OK" if actual == expected else "MISMATCH"
            sf       = result["success_frame"]
            variance = result["joint_pos_variance_mean"]
            print(f"  [{result['id']}] frames={n_frames}  "
                  f"episode_reward={ep_total:+.1f}  expected={expected}  [{status}]  "
                  f"success_frame={sf}  variance={variance:.4f}")

        all_results.extend(batch_results)
        seq_idx += active_count

    output = {
        "version":     "1.0",
        "replayed_at": datetime.datetime.now().isoformat(),
        "source":      args.input,
        "config":      cfg,
        "sequences":   all_results,
    }
    save_replay(output, args.output)


if __name__ == "__main__":
    main()
