"""Tool 2 — Sequence Replayer (Newton FK + full physics).

Replays sequences generated by generate_sequences.py, driving a fresh Newton
physics model with the recorded joint_pos_cmd targets, then computing per-frame
rewards and writing them to a JSON output file.

Architecture
------------
Runs fully standalone using Newton physics — no Isaac Sim / AppLauncher required.

Robot motion: PD controller tracks the recorded joint_pos_cmd targets exactly
  as in the generator.  This is equivalent to FK: the robot follows the same
  joint-angle trajectory that was commanded during generation.

Cube physics: full Newton physics simulation — gravity, contact forces, friction.
  No analytic cube teleportation or kinematic overrides.

Physics model mirrors the generator's phys_model exactly:
  - Same PD gains, armature, effort limits
  - Same gravity compensation (mujoco:jnt_actgravcomp + mujoco:gravcomp)
  - Same finger BOX shapes + collision groups
  - Same contact parameters (ke, kd, kf, mu)
  - Same solver (SolverMuJoCo, impratio=1000, cone=elliptic)
  - Same substep count: 20 × 2ms per recorded frame
    (generator: 10 substeps per outer step × record_every=2 outer steps = 20 substeps)

Usage
-----
python replay_sequences.py \\
    --input  data/validation/sequences.json \\
    --output data/validation/replay.json \\
    [--sequence_id seq_0003]   # replay a single sequence (default: all)
"""

import argparse
import datetime
import json
import sys
from pathlib import Path

import numpy as np
import torch
import warp as wp

import newton

sys.path.insert(0, str(Path(__file__).parent))
from _common.reward_eval import REWARD_WEIGHTS, compute_all_rewards
from _common.sequence_schema import (
    expected_high_reward,
    label_description,
    load_sequences,
    save_replay,
)


_TASK_ROOT   = Path(__file__).parent.parent
_OUTPUTS_DIR = _TASK_ROOT / "data" / "validation"

# ---------------------------------------------------------------------------
# Panda URDF (same candidate list as generator)
# ---------------------------------------------------------------------------

_FRANKA_URDF_CANDIDATES = [
    Path(
        "/home/horde/micromamba/envs/env_isaaclab/lib/python3.11/site-packages/"
        "isaacsim/exts/isaacsim.asset.importer.urdf/data/urdf/robots/"
        "franka_description/robots/panda_arm_hand.urdf"
    ),
]

_PANDA_HAND_BODY_LABEL = "panda/panda_hand"

# ---------------------------------------------------------------------------
# Physics constants — MUST match generate_sequences.py exactly
# ---------------------------------------------------------------------------

# PD gains — matching example_ik_cube_stacking.py
_ARM_KE          = [4500, 4500, 3500, 3500, 2000, 2000, 2000]
_ARM_KD          = [450,  450,  350,  350,  200,  200,  200]
_FINGER_KE       = [100,  100]
_FINGER_KD       = [10,   10]
_ARM_ARMATURE    = [0.30, 0.30, 0.30, 0.30, 0.11, 0.11, 0.11]
_FINGER_ARMATURE = [0.15, 0.15]
_ARM_EFFORT      = [87.0, 87.0, 87.0, 87.0, 12.0, 12.0, 12.0]
_FINGER_EFFORT   = [100.0, 100.0]

# Contact parameters
_CONTACT_KE  = 5.0e4   # N/m   normal spring stiffness
_CONTACT_KD  = 5.0e2   # N·s/m normal damping
_CONTACT_KF  = 1.0e3   # N/m   tangential (friction) spring stiffness
_CONTACT_MU  = 0.75    # friction coefficient

# Robot joint count
_N_ROBOT_JOINTS = 9

# Cube rigid body properties
_CUBE_HALF_SIZE = 0.025
_CUBE_DENSITY   = 400.0   # kg/m³

# Substeps per recorded frame.
# Generator: 10 substeps per outer step, records every 2 outer steps
#   → 20 substeps of 2ms = 40ms between consecutive recorded frames.
# Replayer uses the even-step command for the full 40ms (minor approximation
# since consecutive IK targets change smoothly).
_SUBSTEPS_PER_FRAME = 20
_SUB_DT             = 0.002   # 2ms per substep


def _find_panda_urdf() -> Path:
    for p in _FRANKA_URDF_CANDIDATES:
        if p.exists():
            return p
    raise FileNotFoundError(
        "Panda URDF not found. Install Isaac Sim pip package or set PANDA_URDF env var."
    )


# ---------------------------------------------------------------------------
# Newton physics setup — mirrors generator's build_models phys_model exactly
# ---------------------------------------------------------------------------


def build_phys_model(urdf_path: Path):
    """Build Newton physics model (robot + cube) for replay.

    Mirrors generator's phys_model setup exactly:
      PD gains, armature, effort limits, gravity compensation,
      finger BOX shapes, collision groups, contact params, solver.

    Returns:
        phys_model:     finalized Newton Model (robot + cube, 16 DOF)
        hand_idx:       body index of panda_hand
        cube_body_idx:  body index of cube
        solver:         Newton solver (SolverMuJoCo)
    """
    mb = newton.ModelBuilder()
    newton.solvers.SolverMuJoCo.register_custom_attributes(mb)
    mb.add_ground_plane()
    mb.add_urdf(str(urdf_path), floating=False, enable_self_collisions=False,
                parse_visuals_as_colliders=False)

    # ---- Gravity compensation ------------------------------------------------
    gravcomp_dof = mb.custom_attributes["mujoco:jnt_actgravcomp"]
    if gravcomp_dof.values is None:
        gravcomp_dof.values = {}
    for dof_idx in range(7):   # arm DOFs 0-6 only
        gravcomp_dof.values[dof_idx] = True

    gravcomp_body = mb.custom_attributes["mujoco:gravcomp"]
    if gravcomp_body.values is None:
        gravcomp_body.values = {}
    for body_idx in range(2, len(mb.body_label)):   # skip world (0) and fixed base (1)
        gravcomp_body.values[body_idx] = 1.0

    # ---- Collision group assignment ------------------------------------------
    _left_finger_body  = next(i for i, lbl in enumerate(mb.body_label) if "leftfinger"  in lbl)
    _right_finger_body = next(i for i, lbl in enumerate(mb.body_label) if "rightfinger" in lbl)
    for _i in range(len(mb.shape_body)):
        if mb.shape_body[_i] >= 0:   # skip ground (body=-1)
            mb.shape_collision_group[_i] = 2

    # ---- Finger BOX shapes ---------------------------------------------------
    _cfg_fbox = newton.ModelBuilder.ShapeConfig()
    _cfg_fbox.ke = _CONTACT_KE
    _cfg_fbox.kd = _CONTACT_KD
    _cfg_fbox.kf = _CONTACT_KF
    _cfg_fbox.mu = _CONTACT_MU

    mb.add_shape_box(
        body=_left_finger_body,
        xform=wp.transform(wp.vec3(0.0, 0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox,
        label="leftfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    mb.add_shape_box(
        body=_right_finger_body,
        xform=wp.transform(wp.vec3(0.0, -0.013, 0.027), wp.quat_identity()),
        hx=0.025, hy=0.013, hz=0.018,
        cfg=_cfg_fbox,
        label="rightfinger_box",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    # ---- PD gains + armature + effort limits ---------------------------------
    all_ke     = _ARM_KE      + _FINGER_KE
    all_kd     = _ARM_KD      + _FINGER_KD
    all_arm    = _ARM_ARMATURE + _FINGER_ARMATURE
    all_effort = _ARM_EFFORT  + _FINGER_EFFORT
    for i in range(_N_ROBOT_JOINTS):
        mb.joint_target_ke[i]    = float(all_ke[i])
        mb.joint_target_kd[i]    = float(all_kd[i])
        mb.joint_armature[i]     = float(all_arm[i])
        mb.joint_effort_limit[i] = float(all_effort[i])

    hand_idx = next(
        i for i, l in enumerate(mb.body_label) if _PANDA_HAND_BODY_LABEL in l
    )

    # ---- Cube rigid body -----------------------------------------------------
    cfg_cube         = newton.ModelBuilder.ShapeConfig()
    cfg_cube.density = _CUBE_DENSITY
    cfg_cube.ke      = _CONTACT_KE
    cfg_cube.kd      = _CONTACT_KD
    cfg_cube.kf      = _CONTACT_KF
    cfg_cube.mu      = _CONTACT_MU

    cube_body_idx = mb.add_body(mass=0.0, label="cube")
    mb.add_shape_box(
        body=cube_body_idx,
        hx=_CUBE_HALF_SIZE, hy=_CUBE_HALF_SIZE, hz=_CUBE_HALF_SIZE,
        cfg=cfg_cube,
        label="cube_shape",
    )
    mb.shape_collision_group[len(mb.shape_body) - 1] = 1

    phys_model = mb.finalize()

    solver = newton.solvers.SolverMuJoCo(
        phys_model,
        solver="newton",
        integrator="implicitfast",
        iterations=20,
        ls_iterations=100,
        nconmax=512,
        njmax=1000,
        cone="elliptic",
        impratio=1000.0,
    )

    return phys_model, hand_idx, cube_body_idx, solver


# ---------------------------------------------------------------------------
# Replay one sequence
# ---------------------------------------------------------------------------


def replay_sequence(
    phys_model,
    hand_idx: int,
    cube_body_idx: int,
    solver,
    seq: dict,
    cfg: dict,
    device: torch.device,
) -> dict:
    """Replay a single sequence using Newton FK + full physics. Returns replay result dict.

    Robot: PD controller tracks recorded joint_pos_cmd targets (FK-equivalent).
    Cube: full Newton physics — gravity, contact forces, friction.

    Args:
        phys_model:     Newton Model with robot + cube (16 DOF).
        hand_idx:       body index of panda_hand.
        cube_body_idx:  body index of cube in phys_model.
        solver:         Newton solver for phys_model.
        seq:            sequence dict from load_sequences().
        cfg:            geometry config dict.
        device:         torch device for reward tensors.
    """
    cx, cy, cz = seq["cube_init_pos_w"]

    success_pos = torch.tensor(cfg["success_ee_position"], device=device, dtype=torch.float32).unsqueeze(0)
    signal_pos  = torch.tensor(cfg["signal_ee_position"],  device=device, dtype=torch.float32).unsqueeze(0)
    robot_pos_w = torch.zeros(1, 3, device=device)

    r_min        = cfg["reachable_radius_min"]
    r_max        = cfg["reachable_radius_max"]
    lift_height  = cfg["lift_height"]
    is_reachable = seq["label"]["reachable"]

    # --- Physics state -------------------------------------------------------
    n_phys = phys_model.joint_coord_count   # 16
    n_dof  = phys_model.joint_dof_count     # 15

    state_0 = phys_model.state()
    state_1 = phys_model.state()
    control = phys_model.control()

    has_collider = hasattr(phys_model, "collider")
    contacts = phys_model.collider() if has_collider else None

    # --- Reset: robot to home, cube to sequence init position ----------------
    default_robot_q = phys_model.joint_q.numpy()[:_N_ROBOT_JOINTS].astype(np.float32)

    joint_q_init = np.zeros(n_phys, dtype=np.float32)
    joint_q_init[:_N_ROBOT_JOINTS] = default_robot_q
    joint_q_init[_N_ROBOT_JOINTS:_N_ROBOT_JOINTS + 3] = [cx, cy, cz]
    joint_q_init[_N_ROBOT_JOINTS + 3:n_phys]          = [0.0, 0.0, 0.0, 1.0]

    state_0.joint_q.assign(joint_q_init)
    state_0.joint_qd.assign(np.zeros(n_dof, dtype=np.float32))

    episode_rewards = {k: 0.0 for k in list(REWARD_WEIGHTS.keys()) + ["total"]}
    frame_results   = []

    frames        = seq["frames"]
    success_frame = -1
    variance_accum = []
    prev_robot_q_replay = default_robot_q.copy()

    for frame_idx, frame in enumerate(frames):
        # Drive robot from recorded joint_pos_cmd (FK-equivalent via PD control)
        joint_pos_cmd = np.array(frame["joint_pos_cmd"], dtype=np.float32)
        cmd_full = np.zeros(n_phys, dtype=np.float32)
        cmd_full[:_N_ROBOT_JOINTS] = joint_pos_cmd
        control.joint_target_pos = wp.array(cmd_full, dtype=wp.float32)

        # 20 substeps of 2ms per recorded frame (matches generator exactly)
        state_0.clear_forces()
        for _sub in range(_SUBSTEPS_PER_FRAME):
            if contacts is not None:
                solver.step(state_0, state_1, control, contacts, _SUB_DT)
            else:
                solver.step(state_0, state_1, control, None, _SUB_DT)
            state_0, state_1 = state_1, state_0

        # Read EE and cube positions from body transforms
        newton.eval_fk(phys_model, state_0.joint_q, state_0.joint_qd, state_0)
        body_q       = state_0.body_q.numpy()
        ee_pos_list  = body_q[hand_idx][:3].tolist()
        cube_pos_now = body_q[cube_body_idx][:3].tolist()

        # Robot joint positions + velocity
        robot_q_replay   = state_0.joint_q.numpy()[:_N_ROBOT_JOINTS].astype(np.float32)
        frame_dt = _SUBSTEPS_PER_FRAME * _SUB_DT   # 40ms between recorded frames
        joint_vel_replay = (robot_q_replay - prev_robot_q_replay) / frame_dt

        # Reward tensors
        ee_pos_w    = torch.tensor(ee_pos_list,          device=device, dtype=torch.float32).unsqueeze(0)
        cube_pos_w  = torch.tensor(cube_pos_now,         device=device, dtype=torch.float32).unsqueeze(0)
        joint_vel   = torch.tensor(joint_vel_replay,     device=device, dtype=torch.float32).unsqueeze(0)
        action_curr = torch.tensor(joint_pos_cmd,        device=device, dtype=torch.float32).unsqueeze(0)
        action_prev = torch.tensor(prev_robot_q_replay,  device=device, dtype=torch.float32).unsqueeze(0)

        rews = compute_all_rewards(
            ee_pos_w=ee_pos_w, cube_pos_w=cube_pos_w, robot_pos_w=robot_pos_w,
            joint_vel=joint_vel, action_curr=action_curr, action_prev=action_prev,
            success_ee_pos=success_pos, signal_ee_pos=signal_pos,
            r_min=r_min, r_max=r_max, lift_height=lift_height,
        )

        frame_rew = {k: float(v[0].item()) for k, v in rews.items()}
        for k in episode_rewards:
            episode_rewards[k] += frame_rew.get(k, 0.0)

        # Success detection
        if success_frame == -1:
            if is_reachable:
                if cube_pos_now[2] > lift_height:
                    success_frame = frame_idx
            else:
                if float(torch.dist(ee_pos_w, signal_pos).item()) < 0.15:
                    success_frame = frame_idx

        # Variance: compare generator's recorded joint_pos vs replay
        gen_robot_q = np.array(frame["joint_pos"], dtype=np.float32)
        variance_accum.append(np.abs(gen_robot_q - robot_q_replay))

        frame_results.append({
            "step":           frame["step"],
            "t":              frame["t"],
            "reachable_mask": frame_rew["reachable_mask"],
            "robot_pos_w":    [0.0, 0.0, 0.0],
            "ee_pos_w":       ee_pos_list,
            "cube_pos_w":     cube_pos_now,
            "rewards":        {k: round(frame_rew[k], 6) for k in REWARD_WEIGHTS},
        })

        prev_robot_q_replay = robot_q_replay

    joint_pos_variance_mean = float(np.mean(np.stack(variance_accum))) if variance_accum else 0.0

    return {
        "id":                      seq["id"],
        "label":                   seq["label"],
        "expected_high_reward":    expected_high_reward(seq["label"]),
        "episode_rewards":         {k: round(v, 4) for k, v in episode_rewards.items()},
        "success_frame":           success_frame,
        "joint_pos_variance_mean": round(joint_pos_variance_mean, 6),
        "frames":                  frame_results,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Replay Franka cube pick sequences with Newton FK + full physics."
    )
    parser.add_argument("--input",       type=str, default=str(_OUTPUTS_DIR / "sequences.json"),
                        help="Path to sequences.json (Tool 1 output).")
    parser.add_argument("--output",      type=str, default=str(_OUTPUTS_DIR / "replay.json"),
                        help="Path for replay output JSON.")
    parser.add_argument("--sequence_id", type=str, default=None,
                        help="If set, replay only this sequence ID. Otherwise replays all.")
    parser.add_argument("--device",      type=str, default="cpu",
                        help="Torch device for reward tensors (cpu/cuda).")
    args = parser.parse_args()

    device = torch.device(args.device)

    urdf_path = _find_panda_urdf()
    print(f"[replay] Loading Panda URDF: {urdf_path}")
    phys_model, hand_idx, cube_body_idx, solver = build_phys_model(urdf_path)
    print(f"[replay] Newton model: {phys_model.body_count} bodies, {phys_model.joint_coord_count} joint coords")
    print(f"[replay] Solver: {type(solver).__name__}")
    print(f"[replay] Substeps: {_SUBSTEPS_PER_FRAME} × {_SUB_DT*1000:.1f}ms = {_SUBSTEPS_PER_FRAME*_SUB_DT*1000:.0f}ms per frame")

    data = load_sequences(args.input)
    cfg  = data["config"]

    sequences = data["sequences"]
    if args.sequence_id is not None:
        sequences = [s for s in sequences if s["id"] == args.sequence_id]
        if not sequences:
            raise ValueError(f"Sequence '{args.sequence_id}' not found in {args.input}")

    results = []
    for i, seq in enumerate(sequences):
        lbl_str = label_description(seq["label"])
        print(f"[replay] {i + 1}/{len(sequences)} — {seq['id']} ({lbl_str})", end="", flush=True)
        result = replay_sequence(phys_model, hand_idx, cube_body_idx, solver, seq, cfg, device)
        results.append(result)

        ep_total  = result["episode_rewards"]["total"]
        expected  = "SUCCESS" if result["expected_high_reward"] else "FAILURE"
        # Use success_frame (task completion) not reward threshold — immune to approach
        # reward accumulating in near-cube failure modes (approach_no_grip, grip_drop_early…).
        actual    = "SUCCESS" if result["success_frame"] >= 0 else "FAILURE"
        status    = "OK" if actual == expected else "MISMATCH"
        sf        = result["success_frame"]
        variance  = result["joint_pos_variance_mean"]
        print(f"  episode_reward={ep_total:+.1f}  expected={expected}  [{status}]"
              f"  success_frame={sf}  variance={variance:.4f}")

    output = {
        "version":     "1.0",
        "replayed_at": datetime.datetime.now().isoformat(),
        "source":      args.input,
        "config":      cfg,
        "sequences":   results,
    }
    save_replay(output, args.output)


if __name__ == "__main__":
    main()
