# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Tool 2 — VBD Sequence Replayer (batched multi-world Newton + VBD physics).

Replays sequences generated by generate_sequences.py using the same VBD physics
(robot + deformable cube), drives the robot with the recorded joint_pos_cmd targets,
and computes per-frame reward terms.

Key differences from the rigid replayer:
  - Cube position comes from particle CoM (not rigid body joint_q)
  - Two-phase stepping: SolverMuJoCo + SolverVBD each substep
  - CollisionPipeline for particle–shape soft contacts
  - VBD reward_utils.py (same math as rigid, different data source name)

Architecture
------------
Runs N worlds simultaneously, mirroring generate_sequences.py exactly.
Model, solver, and collision pipeline are imported from generate_sequences.py
so physics is guaranteed identical between generation and replay.

Usage
-----
micromamba run -n env_isaaclab python scripts/replay_sequences.py \\
    --input  data/validation/vbd_sequences.json \\
    --output data/validation/vbd_replay.json \\
    [--num-worlds 4]
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import numpy as np
import torch
import warp as wp

import newton

sys.path.insert(0, str(Path(__file__).parent))
from _common.reward_eval import REWARD_WEIGHTS, compute_all_rewards
from _common.sequence_schema import (
    expected_high_reward,
    label_description,
    load_sequences,
    save_replay,
)

# Import VBD physics from generate_sequences (single source of truth for model building)
from generate_sequences import (
    _HOME_JOINT_Q,
    _MAX_CONTACTS_PER_ENV,
    _N_ROBOT_JOINTS,
    _N_SUBSTEPS,
    _PARTICLE_RADIUS,
    _SUB_DT,
    build_robot_builder,
    build_vbd_batched_model,
    get_cube_coms_np,
    reset_batch_state,
    simulate_two_phase,
)

_TASK_ROOT   = Path(__file__).parent.parent
_OUTPUTS_DIR = _TASK_ROOT / "data" / "validation"


# ---------------------------------------------------------------------------
# Batch replay
# ---------------------------------------------------------------------------

def run_batch_replay(
    model,
    rigid_solver, vbd_solver, collision, soft_contacts,
    hand_local_idx: int,
    num_bodies_per_world: int,
    num_worlds: int,
    state_0, state_1, control,
    n_particles: int,
    particle_rest_q: np.ndarray,
    batch_seqs: list,
    active_count: int,
    cfg: dict,
    device: torch.device,
) -> list:
    """Replay active_count sequences simultaneously. Returns list of active_count result dicts."""
    n_coord_per_world = model.joint_coord_count // num_worlds
    n_ctrl_per_world  = len(control.joint_target_pos) // num_worlds

    n_frames    = len(batch_seqs[0]["frames"])
    r_min       = cfg["reachable_radius_min"]
    r_max       = cfg["reachable_radius_max"]
    lift_height = cfg["lift_height"]

    success_pos   = torch.tensor(cfg["success_ee_position"], device=device, dtype=torch.float32)
    signal_pos    = torch.tensor(cfg["signal_ee_position"],  device=device, dtype=torch.float32)
    robot_pos_t   = torch.zeros(num_worlds, 3, device=device)
    success_pos_t = success_pos.unsqueeze(0).expand(num_worlds, -1)
    signal_pos_t  = signal_pos.unsqueeze(0).expand(num_worlds, -1)

    default_robot_q = np.array(_HOME_JOINT_Q, dtype=np.float32)

    episode_rewards  = [{k: 0.0 for k in list(REWARD_WEIGHTS.keys()) + ["total"]}
                        for _ in range(num_worlds)]
    success_frames   = [-1] * num_worlds
    variance_accum   = [[] for _ in range(num_worlds)]
    frame_results_pw = [[] for _ in range(num_worlds)]
    prev_robot_q     = np.tile(default_robot_q, (num_worlds, 1))

    frame_dt = _N_SUBSTEPS * _SUB_DT

    for frame_idx in range(n_frames):
        # 1. Set joint targets from recorded commands
        ctrl_np = np.zeros((num_worlds, n_ctrl_per_world), dtype=np.float32)
        for w in range(num_worlds):
            ctrl_np[w, :_N_ROBOT_JOINTS] = batch_seqs[w]["frames"][frame_idx]["joint_pos_cmd"]
        control.joint_target_pos.assign(ctrl_np.reshape(-1))

        # 2. Two-phase physics step
        state_0, state_1 = simulate_two_phase(
            state_0, state_1,
            rigid_solver, vbd_solver, collision, soft_contacts,
            None, control, _SUB_DT, _N_SUBSTEPS,
        )

        # 3. Read state (one GPU→CPU sync)
        newton.eval_fk(model, state_0.joint_q, state_0.joint_qd, state_0)
        body_q_np     = state_0.body_q.numpy()
        joint_q_np    = state_0.joint_q.numpy()
        particle_q_np = state_0.particle_q.numpy()
        if particle_q_np.ndim == 1:
            particle_q_np = particle_q_np.reshape(-1, 3)

        # 4. Extract per-world observations
        ee_pos_np   = np.empty((num_worlds, 3), dtype=np.float32)
        robot_q_np  = np.empty((num_worlds, _N_ROBOT_JOINTS), dtype=np.float32)
        for w in range(num_worlds):
            gh = w * num_bodies_per_world + hand_local_idx
            ee_pos_np[w] = body_q_np[gh][:3]
            base = w * n_coord_per_world
            robot_q_np[w] = joint_q_np[base : base + _N_ROBOT_JOINTS]

        cube_coms   = get_cube_coms_np(particle_q_np, num_worlds, n_particles)  # (N, 3)
        gripper_width_np = robot_q_np[:, 7] + robot_q_np[:, 8]
        joint_vel_np = (robot_q_np - prev_robot_q) / frame_dt

        # 5. Vectorised reward computation
        ee_pos_t        = torch.tensor(ee_pos_np,        device=device, dtype=torch.float32)
        cube_pos_t      = torch.tensor(cube_coms,        device=device, dtype=torch.float32)
        gripper_width_t = torch.tensor(gripper_width_np, device=device, dtype=torch.float32)
        joint_vel_t     = torch.tensor(joint_vel_np,     device=device, dtype=torch.float32)
        action_curr_t   = torch.tensor(ctrl_np[:, :_N_ROBOT_JOINTS], device=device, dtype=torch.float32)
        action_prev_t   = torch.tensor(prev_robot_q,     device=device, dtype=torch.float32)

        rews = compute_all_rewards(
            ee_pos_w=ee_pos_t, cube_pos_w=cube_pos_t, robot_pos_w=robot_pos_t,
            gripper_width=gripper_width_t,
            joint_vel=joint_vel_t, action_curr=action_curr_t, action_prev=action_prev_t,
            success_ee_pos=success_pos_t, signal_ee_pos=signal_pos_t,
            r_min=r_min, r_max=r_max, lift_height=lift_height,
        )

        # 6. Per-world bookkeeping
        for w in range(num_worlds):
            frame_rew = {k: float(v[w].item()) for k, v in rews.items()}
            for k in episode_rewards[w]:
                episode_rewards[w][k] += frame_rew.get(k, 0.0)

            if success_frames[w] == -1:
                if batch_seqs[w]["label"]["reachable"]:
                    if cube_coms[w, 2] > lift_height:
                        success_frames[w] = frame_idx
                else:
                    if float(torch.dist(ee_pos_t[w], signal_pos).item()) < 0.15:
                        success_frames[w] = frame_idx

            gen_robot_q = np.array(batch_seqs[w]["frames"][frame_idx]["joint_pos"], dtype=np.float32)
            variance_accum[w].append(np.abs(gen_robot_q - robot_q_np[w]))

            frame_results_pw[w].append({
                "step":           batch_seqs[w]["frames"][frame_idx]["step"],
                "t":              batch_seqs[w]["frames"][frame_idx]["t"],
                "reachable_mask": frame_rew.get("reachable_mask", 0.0),
                "robot_pos_w":    [0.0, 0.0, 0.0],
                "ee_pos_w":       ee_pos_np[w].tolist(),
                "cube_pos_w":     cube_coms[w].tolist(),
                "rewards":        {k: round(frame_rew[k], 6) for k in REWARD_WEIGHTS},
            })

        prev_robot_q = robot_q_np.copy()

    # Build result dicts
    results = []
    for w in range(active_count):
        var_mean = float(np.mean(np.stack(variance_accum[w]))) if variance_accum[w] else 0.0
        results.append({
            "id":                      batch_seqs[w]["id"],
            "label":                   batch_seqs[w]["label"],
            "expected_high_reward":    expected_high_reward(batch_seqs[w]["label"]),
            "episode_rewards":         {k: round(v, 4) for k, v in episode_rewards[w].items()},
            "success_frame":           success_frames[w],
            "joint_pos_variance_mean": round(var_mean, 6),
            "frames":                  frame_results_pw[w],
        })
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Replay Franka VBD cube pick sequences with two-phase Newton+VBD physics."
    )
    parser.add_argument("--input",       type=str, default=str(_OUTPUTS_DIR / "vbd_sequences.json"))
    parser.add_argument("--output",      type=str, default=str(_OUTPUTS_DIR / "vbd_replay.json"))
    parser.add_argument("--num-worlds",  type=int, default=4,
                        help="Batch size (default 4 for VBD).")
    parser.add_argument("--sequence_id", type=str, default=None)
    parser.add_argument("--device",      type=str, default="cpu")
    args = parser.parse_args()

    device = torch.device(args.device)

    from generate_sequences import _find_panda_urdf
    urdf_path = _find_panda_urdf()
    print(f"[vbd_replay] Panda URDF: {urdf_path}")
    print(f"[vbd_replay] Building VBD batched model (num_worlds={args.num_worlds}) ...")

    robot_mb, hand_local_idx, _ = build_robot_builder(urdf_path)
    (model, rigid_solver, vbd_solver, collision, soft_contacts,
     n_particles, particle_rest_q) = build_vbd_batched_model(robot_mb, args.num_worlds)

    num_bodies_per_world = model.body_count // args.num_worlds
    print(f"[vbd_replay] hand_local_idx={hand_local_idx}  "
          f"bodies/world={num_bodies_per_world}  particles/world={n_particles}")

    data      = load_sequences(args.input)
    cfg       = data["config"]
    sequences = data["sequences"]

    if args.sequence_id is not None:
        sequences = [s for s in sequences if s["id"] == args.sequence_id]
        if not sequences:
            raise ValueError(f"Sequence '{args.sequence_id}' not found in {args.input}")

    num_worlds = args.num_worlds
    state_0    = model.state()
    state_1    = model.state()
    control    = model.control()

    default_robot_q = np.array(_HOME_JOINT_Q, dtype=np.float32)
    n_seq    = len(sequences)
    n_frames = len(sequences[0]["frames"])
    n_batch  = (n_seq + num_worlds - 1) // num_worlds

    print(f"[vbd_replay] Replaying {n_seq} sequences in batches of {num_worlds} "
          f"| {n_frames} frames × {_N_SUBSTEPS * _SUB_DT * 1000:.0f}ms = "
          f"{n_frames * _N_SUBSTEPS * _SUB_DT:.1f}s per sequence")

    all_results = []
    seq_idx = 0

    for batch_num in range(n_batch):
        active_count = min(num_worlds, n_seq - seq_idx)
        pad_count    = num_worlds - active_count

        batch_seqs = sequences[seq_idx : seq_idx + active_count]
        if pad_count > 0:
            batch_seqs = batch_seqs + [batch_seqs[0]] * pad_count

        desc = " | ".join(
            f"{s['id']}({label_description(s['label'])})"
            for s in batch_seqs[:active_count]
        )
        print(f"[vbd_replay] batch {batch_num + 1}/{n_batch} "
              f"({active_count} active): {desc}", flush=True)

        # Reset
        cube_positions = np.array([s["cube_init_pos_w"] for s in batch_seqs], dtype=np.float32)
        reset_batch_state(
            model, state_0, state_1,
            cube_positions, default_robot_q, None,
            num_worlds, n_particles, particle_rest_q,
        )
        newton.eval_fk(model, state_0.joint_q, state_0.joint_qd, state_0)

        batch_results = run_batch_replay(
            model=model,
            rigid_solver=rigid_solver, vbd_solver=vbd_solver,
            collision=collision, soft_contacts=soft_contacts,
            hand_local_idx=hand_local_idx,
            num_bodies_per_world=num_bodies_per_world,
            num_worlds=num_worlds,
            state_0=state_0, state_1=state_1, control=control,
            n_particles=n_particles, particle_rest_q=particle_rest_q,
            batch_seqs=batch_seqs,
            active_count=active_count,
            cfg=cfg,
            device=device,
        )

        for w, result in enumerate(batch_results):
            ep_total = result["episode_rewards"]["total"]
            expected = "SUCCESS" if result["expected_high_reward"] else "FAILURE"
            actual   = "SUCCESS" if result["success_frame"] >= 0 else "FAILURE"
            status   = "OK" if actual == expected else "MISMATCH"
            variance = result["joint_pos_variance_mean"]
            print(f"  [{result['id']}] ep_reward={ep_total:+.1f}  "
                  f"expected={expected}  [{status}]  "
                  f"success_frame={result['success_frame']}  variance={variance:.4f}")

        all_results.extend(batch_results)
        seq_idx += active_count

    output = {
        "version":     "1.0",
        "replayed_at": datetime.datetime.now().isoformat(),
        "source":      args.input,
        "config":      cfg,
        "sequences":   all_results,
    }
    save_replay(output, args.output)


if __name__ == "__main__":
    main()
